### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [JakeCrandell/proj10-models#1]
I'm not huge into baseball, so correct me if I'm wrong, but can't a player technically have a batting average of up to 4.0 (possible only if they've home-runned every pitch thrown at them)? In a case like this, the instructions to `Only enter the digits of the players average, no decimals or 0. before it.` could be invalid. Since this field is of decimal type anyway, it seems like it would make sense to include the `0.` for most players. As an alternative validation for this field, I would make sure that the number is greater than or equal to 0 and less than or equal to 4. What do you think? Like I said, I don't know a lot about baseball, so feel free to let me know if this doesn't make sense.

There's a similar validation issue for age. The length you're checking for is 2, but since this app doesn't specify that these are MLB players or something similar, an 8-year-old could technically be a baseball player in some league, right? Or if you do want to specify MLB players, maybe check that the age is at least 16 or whatever the minimum age for that league is.

Let me know if you think these changes make sense.

**Comment by JakeCrandell** [comment]
Ok, so I changed the age validations so they have to be at least 17. Now for the average, I've been playing around with it for a little while and I can't get it to display right. Batting average is just (how many times you get on base) divided by (how many times you went up to the plate). So, if I go up to the plate 10 times and get on base 3 times, then my batting average is .300 (3/10). The average should not be displayed as xxx.0, that is actually not the correct way to show batting average, but it was the only way I could make it look decent. I made that attribute a decimal cause I wanted it to display as .xxx, but every time I enter that in the form it accepts it, it just displays the .xxx I entered along with 00000000000003678534 attached to it. Any hints on how I can make it display correctly? Why does it add all those extra numbers?

**Comment by chrisvfritz** [comment]
> The average should not be displayed as xxx.0, that is actually not the correct way to show batting average, but it was the only way I could make it look decent. I made that attribute a decimal cause I wanted it to display as .xxx

If I'm understanding correctly, the best way to get this to display correctly would probably be using the [`number_with_precision`](http://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html#method-i-number_with_precision) helper method in Rails and then chopping off the first character (which should be a 0), if the number is less than 1. Try defining something like the following in your baseballs helper and then using it on the views for `index` and `show`.

``` ruby
def format_batting_average(number)
  average = number_with_precision number, precision: 3
  number < 1 ? average[1..-1] : average
end
```

To use it in your view, you could just do something changing [this line](https://github.com/JakeCrandell/proj10-models/blob/master/app/views/baseballs/show.html.erb#L20) to:

``` erb
<%= format_batting_average @baseball.batting_average %>
```

> it just displays the .xxx I entered along with 00000000000003678534 attached to it

Does this also happen on Heroku or only on your machine? SQLite3 might be using a Float internally instead of a Decimal, which is much faster, but less accurate, and sometimes causes these kinds of weird inaccuracies.

**Comment by JakeCrandell** [comment]
Thank you! That seems to have fixed my problem. To answer your question, Heroku seemed to handle the problems better, but it would show an average of .200 as .2, it would cut off the zeros. That was also fixed with the number_with_precision helper, though. So, I think the age and batting average are both good, unless I missed something.

**Comment by chrisvfritz** [comment]
:+1: Excellent! I did a little more research and it does appear that the problem is related to SQLite3 not having a _true_ decimal data type and also experiencing decimal to floating point conversion errors on some systems. :smiley:
